# Project Question {#Project Question}

UDOT maintains a vast network of highways within the State of Utah. Many hazards (both manmade and naturally occurring) exist that threaten the integrity of these systems. Much is already known about the effects disasters can have on transportation systems, such as changes in route choice, travel time, and transit ridership. Recent disasters, such as the Minneapolis Bridge Collapse and the Atlanta Bridge Fire, have given researchers the opportunity to better evaluate these changes in recent years. Researchers employed numerous methods to analyze and understand the regional impacts of these events. However, one tool that is not well represented in current research is traffic forecasting and planning software. Programs such as Citilabs' CUBE possess unique capabilies to analyze more types of data all at once through logit modeling, rather than separately as has been done in existing research. This project seeks to determine if logit modeling can better predict the impacts of adverse effects on transportation systems by using socioeconomic data gathered during the 2010 US Census to forecast changes in destination choice. It is hypothesized that by comparing changes in forecasted travel between transportation analysis zones (TAZs), a better prediction of the changes to driver behavior, and thus destination choice, can be made.



