# Methodology

## Input Data
This section will be added shortly, I don't currently have easy access to csv's or dbf's of the input data at the time of writing. Hopefully, I'll get it added before Dr. Macfarlane reviews this (although he knows which data I've been using).

## Demonstration Model Framework

Figure # show a schematic of the model framework. The framework has three main inputs:	
A. Highway Network: The USTM model network was obtained from UDOT and forms the basis of the model.
B. Productions: Zonal trip productions from the USTM model
C. Attractions: Zonal trip attractions from the USTM model
 
>insert figure of model here  
  
The model individually calculates mode choice and destination choice logsum values for each trip purpose, and then combines these outputs together. Thus, steps 3 and 4 of the model contain “children” processes with several groups of repeated code, once for each trip purpose. 

The mode choice model framework currently implemented is based on the Roanoke, Virginia travel model that serves as a basis for much of the code in the model. The USTM mode choice model uses similar alternatives and parameters, and we anticipate conflating and combining these coefficients in the next few weeks. The mode choice model includes utility parameters for in-vehicle travel time, out-of-vehicle travel time, wait time, automobile operating cost, and other elements for each trip purpose. The mode choice alternatives are drive alone, shared ride, non-motorized, and transit (all modes). USTM relies on MPO-level mode choice models to handle transit use, but in this application, it is important to consider transit as an available alternative. Work is underway to convert the minimum WFRC transit skim among all modes into a single “transit” skim at the USTM zone level.

The destination choice model uses the same purposes as the mode choice model, with utility equation coefficients including the zonal attractions as a size term and the mode choice log sum as an impedance term. The current demonstration model uses destination choice parameters and calibration constants derived from the Roanoke, Virginia model. Research into destination choice utility coefficients used in statewide models is ongoing, and a minimal calibration exercise will be reported at the next TAC meeting.

The outputs are then combined to create a single file with all of the destination choice log sum accessibility outputs. The final output of the model is the destination choice log sum. 

>An example output can be seen in #####

## Simulating a Broken Link Within the Demonstration Model
We conducted a sensitivity analysis where we simulated a broken highway link in our demonstration model to verify that the model was responding in an appropriate way. Figure 4 shows the change in the log sum value for each purpose resulting from breaking a single highway link across all trip purposes. In order to simulate the changes caused by a broken link, a link was removed from the network file; the model then uses updated highway travel times to compute the mode and destination choice log sums. In general, the change in log sums shows a reasonable response, but the link selected is a major facility for travel in all directions through Roanoke. We are currently investigating whether these unexpected results are the result of improper specification, or whether they reveal a genuine nuance within this particular application technique. 

>add image of the choropleth maps here

## Identifying Vulnerable Links
It is necessary for us to identify links in the UTSM network whose breaks we could simulate in our analysis. The AEM (2017) study inspiring this current work identified nine physical threat categories and locations of elevated risk to highway facilities on the I-15 corridor; the present analysis requires that we identify highway links at risk anywhere in Utah, and thus cannot rely only on the identification completed by AEM. An alternative method to identifying links vulnerable to specific risks would be to simply make arbitrary cuts in the network at locations the TAC identifies that could be representative of unknown threats or suspected choke points in the USTM network. The Risk Priority Analysis completed by BIO-WEST (2020) shows Composite Threat Probability by Road Segment. We used this analysis to identify 40 locations in the UTSM network that are either posed with an elevated annual threat or identified as a choke point. We also desired to have a mix of urban and rural facilities to demonstrate the potential flexibility of our proposed technique. 
>The selected locations are shown in Figure 5.


