---
title: Crater Lake
---

## Setup 

```{r setup, message = FALSE}
library(tidyverse)
```

Some custom colors for ggplot2 plots:
```{r colors}
my_colors <- c(
  light = "#F8F5F0",
  dark = "#3E3F3A",
  blue = "#325D88",
  grey = "#8E8C84"
)

theme_set(theme_grey(base_size = 18))
theme_update(
  panel.background = element_rect(fill = my_colors["light"]), 
  text = element_text(color = my_colors["dark"])
)

update_geom_defaults("line", list(color = my_colors["dark"]))
```

## Data Import

```{r import}
annual_visits <- read_rds("data/annual_visits.rds")
monthly_visits <- read_rds("data/monthly_visits.rds")
```

```{r data-preview}
head(annual_visits, n = 5)
head(monthly_visits, n = 5)
```

## 2019 Summary

```{r summary}
# Function to form a one sentence summary from a year
# of annual data
summarize_park <- function(one_year){
  comma <- scales::label_comma()
  one_year %>% 
    glue::glue_data(
    "In { year }, { park_name } had { comma(recreation_visits) } recreation visits."
  )
}

annual_visits %>% 
  filter(park_name == "Crater Lake NP") %>% 
  filter(year == 2019) %>% 
  summarize_park()
```

## Annual visits

```{r annual}
annual_visits %>% 
  filter(park_name == "Crater Lake NP") %>% 
  ggplot(aes(year, recreation_visits)) +
    geom_point(data = ~ filter(., year == 2019)) +
    geom_line() +
    scale_y_continuous(labels = scales::label_comma()) +
    labs(x = "", y = "Visits")
```

## Monthly visits

```{r monthly}
monthly_visits %>% 
  filter(park_name == "Crater Lake NP") %>% 
  ggplot(aes(month, recreation_visits_proportion)) +
    geom_line(aes(group = year), alpha = 0.2) +
    geom_line(data = ~ filter(.x, year == 2019)) +
    stat_summary(fun = mean, 
      geom = "line", color = "#325D88", size = 1.5) +
    scale_x_continuous(breaks = 1:12, labels = month.abb) +
    scale_y_continuous(labels = scales::label_percent()) +
    labs(x = "", y = "Of Annual Visits")
```

In 2019,
```{r}
monthly_visits %>% 
  filter(park_name == "Crater Lake NP") %>% 
  filter(year == 2019) %>% 
  select(month_name, recreation_visits)
```

