---
title: "Quarterly Dwelling Sales Report"
output: 
  pdf_document:
    toc: yes
  html_document:
    toc: yes
---

```{r setup, include=FALSE}
library(tidyverse)
library(knitr)
```
## Data Import

```{r import, echo = FALSE, results = "hide", message = FALSE}
# generate some fake data that looks like the real data
sales <- read_csv("data/property_sales.csv")

# first five rows of fake data
head(x = sales, n = 5)

# number of rows of fake data
total_sales <- nrow(sales)
```

A total of `r total_sales` 1383* property sales were inported from `property_sales.csv`


```{r dwelling-data, include = FALSE}

# keep just "Dwelling" sales
dwelling_sales <- filter(sales, 
  property_class == "Dwelling")

# percentage of sales that are dwellings
dwelling_percent <- (nrow(dwelling_sales) / total_sales) * 100
```



Of all the sales, `r round(dwelling_percent)`% were dwellings.

```{r summary, echo = FALSE}
# average price by neighborhood
dwelling_summary <- dwelling_sales %>% 
  group_by(neighborhood) %>% 
  summarize(
    n_sales = n(),
    mean_price = mean(sales_price),
    median_price = median(sales_price)
  ) %>% 
  arrange(median_price)

write_csv(dwelling_summary,"results/dwelling_summary.csv")
dwelling_summary %>% kable()
```


```{r plot, summary = FALSE, message = FALSE, fig.width = 8, fig.height = 4.5}
# plot all sale prices by neighborhood
dwelling_sales %>% 
ggplot(aes(sales_price)) +
  geom_histogram() + 
  scale_x_log10(labels = scales::label_dollar()) +
  facet_wrap(~ neighborhood, scale = "free_y") +
  labs(
    x = "Sales price",
    y = "Number of sales"
  )
ggsave("results/sales_histograms.png", height = 8, width = 4.5)
```

